version: '2'

services:
    web_server:
        image: nginx:1.17.2
        container_name: nginx
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - ./nginx/conf/vhosts:/etc/nginx/conf.d
            - ./nginx/conf/nginx.conf:/etc/nginx/nginx.conf
            - ./www:/usr/share/nginx/html
            - ./nginx/logs:/var/log/nginx
        networks:
            - web
            
    php:
        build: ./php
        image: php:mysql_connect
        container_name: php
        ports:
            - "9000:9000"
        volumes:
            - ./www:/var/www/html
        networks:
            - web
            
    # db_server:
    #     image: mysql:5.7.27
    #     container_name: mysql
    #     environment:
    #         MYSQL_ROOT_PASSWORD: mmlrocks10000
    #     ports:
    #         - "3306:3306"
    #     command: [
    #         '--character-set-server=utf8mb4',
    #         '--collation-server=utf8mb4_unicode_ci'
    #     ]  
    #     volumes:
    #         - ./mysql:/var/lib/mysql
    #     networks:
    #         - web
        
networks:
    web:
        driver: bridge